### ISSUE TITLE
CentOS 7.3: bootstrap class path not set in conjunction with -source 1.6

### ISSUE THREAD

**Issue by ephracis** [OpenAttestation/OpenAttestation#57]
When I try to compile on CentOS 7.3 by running `mvn clean install -DskipTests=true` I get the following error:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project ASData: Compilation failure
[ERROR] bootstrap class path not set in conjunction with -source 1.6
[ERROR] /usr/local/src/openattestation/services/ASData/src/main/java/com/intel/mtwilson/as/data/MwAssetTagCertificate.java:[23,24] error: cannot find symbol
```
